In [6]:
import numpy as np

m is number of features  
n is number of training examples  
X is of dimension (m,n) and Y is of dimension (m,1)

In [20]:
class lin_reg:
    '''Model that does linear regression on the data'''
    
    def train(self, X, Y, alpha = 0.0001):
        '''Train the model on a dataset from the examples X and the labels Y.
        The algorithm uses gradient descent with learning rate alpha for a max of 1000000 steps.
        X must in the format (# examples)x(# features) and Y is a column array.
        The final weights as well as a list of the costs calculated through the training 
        can be extracted using methods .weights and .cost.'''
        
        # Extract number of training examples and features from X
        (m, n) = X.shape
        # Add a column of ones to X for the bias
        X = np.append(np.ones((m,1)), X, axis = 1)
        Y = np.reshape(Y, (m,1))
        # Initialize the weights to zero
        self.weights = np.zeros((n+1 ,1))
        # Initialize the cost
        i = 0
        self.cost = []
        self.cost.append(1/m * np.matmul(np.transpose(Y - np.matmul(X, self.weights)), Y - np.matmul(X, self.weights)))
        # Update weights with gradient and compute new cost
        while True:
            self.weights = self.weights + alpha / m * np.matmul(np.transpose(X), Y - np.matmul(X, self.weights))
            self.cost.append(1/m * np.matmul(np.transpose(Y - np.matmul(X, self.weights)), Y - np.matmul(X, self.weights)))
            # Stop upgrading if cost doesn't lower of if reached limit
            if self.cost[i + 1] < self.cost[i]:
                i += 1
            else:
                break
            if i > 1000000:
                print('Gradient descent did not converge fast enough')
                break

    def predict(self, X):
        '''Use data X and trained model to predict labels using linear regression hypothesis.'''
    
        # Extract number of training examples and features from X
        (m, n) = X.shape
        # Add a column of ones to X for the bias
        X = np.append(np.ones((m,1)), X, axis = 1)
        return np.matmul(X, self.weights)

In [4]:
from sklearn.datasets import load_boston
from sklearn.linear_model import LinearRegression
data = load_boston()

In [7]:
model = lin_reg()
model.train(data['data'], data['target'], alpha=0.000001)
model.cost[:15:]

Gradient descent did not converge fast enough


[array([[592.146917]]),
 array([[349.66048201]]),
 array([[233.95288997]]),
 array([[178.13637393]]),
 array([[150.64094942]]),
 array([[136.56476656]]),
 array([[128.87251857]]),
 array([[124.24157953]]),
 array([[121.10160955]]),
 array([[118.70935353]]),
 array([[116.71199328]]),
 array([[114.94106971]]),
 array([[113.31522125]]),
 array([[111.79427765]]),
 array([[110.35759086]])]

In [21]:
mod = lin_reg()

In [177]:
mod.train()